"use client";
import{ChangeEvent,useEffect,useMemo,useRef,useState}from"react";
import{nextTrackId,previousTrackId,RepeatMode}from"@/lib/queue";
import{formatBytes,importTracks,listTracks,removeTrack,Track}from"@/lib/tracks";
type Playlist={id:string;name:string;trackIds:string[]};
export function MusicLibrary(){
 const[tracks,setTracks]=useState<Track[]>([]),[query,setQuery]=useState(""),[current,setCurrent]=useState<Track|null>(null),[audioUrl,setAudioUrl]=useState<string>(),[busy,setBusy]=useState(true),[shuffle,setShuffle]=useState(false),[repeat,setRepeat]=useState<RepeatMode>("off"),[playlists,setPlaylists]=useState<Playlist[]>([]),[activePlaylist,setActivePlaylist]=useState("all"),[addingTrack,setAddingTrack]=useState<Track|null>(null);const input=useRef<HTMLInputElement>(null);
 const refresh=async()=>setTracks(await listTracks());
 useEffect(()=>{refresh().finally(()=>setBusy(false))},[]);
 useEffect(()=>{try{setPlaylists(JSON.parse(localStorage.getItem("mp3-shelf-playlists")??"[]"))}catch{setPlaylists([])}},[]);
 useEffect(()=>{localStorage.setItem("mp3-shelf-playlists",JSON.stringify(playlists))},[playlists]);
 useEffect(()=>()=>{if(audioUrl)URL.revokeObjectURL(audioUrl)},[audioUrl]);
 const playlist=playlists.find(item=>item.id===activePlaylist);
 const queue=useMemo(()=>playlist?tracks.filter(track=>playlist.trackIds.includes(track.id)):tracks,[playlist,tracks]);
 const visible=useMemo(()=>queue.filter(track=>track.name.toLowerCase().includes(query.toLowerCase().trim())),[queue,query]);
 async function onImport(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files??[]);if(!files.length)return;setBusy(true);try{await importTracks(files);await refresh()}finally{setBusy(false);event.target.value=""}}
 function play(track:Track){if(audioUrl)URL.revokeObjectURL(audioUrl);setCurrent(track);setAudioUrl(URL.createObjectURL(track.blob))}
 function move(direction:"next"|"previous"){if(!current)return;const ids=queue.map(track=>track.id),id=direction==="next"?nextTrackId(ids,current.id,{shuffle,repeat}):previousTrackId(ids,current.id),target=tracks.find(track=>track.id===id);if(target)play(target)}
 async function remove(track:Track){await removeTrack(track.id);setPlaylists(items=>items.map(item=>({...item,trackIds:item.trackIds.filter(id=>id!==track.id)})));if(current?.id===track.id){setCurrent(null);setAudioUrl(undefined)}await refresh()}
 function createPlaylist(){const name=window.prompt("Playlist name")?.trim();if(!name)return;const id=crypto.randomUUID();setPlaylists(items=>[...items,{id,name,trackIds:[]}]);setActivePlaylist(id)}
 function addToPlaylist(playlistId:string,trackId:string){setPlaylists(items=>items.map(item=>item.id===playlistId&&!item.trackIds.includes(trackId)?{...item,trackIds:[...item.trackIds,trackId]}:item));setAddingTrack(null)}
 function deleteActivePlaylist(){if(activePlaylist==="all")return;setPlaylists(items=>items.filter(item=>item.id!==activePlaylist));setActivePlaylist("all")}
 function cycleRepeat(){setRepeat(mode=>mode==="off"?"all":mode==="all"?"one":"off")}
 return <main className="shell"><header className="topbar"><div className="brand-mark">♫</div><div><p className="eyebrow">YOUR OFFLINE LIBRARY</p><h1>MP3 Shelf</h1></div><button className="add-small" onClick={()=>input.current?.click()} aria-label="Import MP3 files">＋</button></header>
 <section className="hero"><p className="eyebrow accent">FILES, WITHOUT THE HUNT</p><h2>Pick them once.<br/>Play them anytime.</h2><p>Choose a whole group of MP3s from Files, then search, organize and play them here.</p><button className="import-button" onClick={()=>input.current?.click()} disabled={busy}>{busy?"Loading…":"Choose MP3s"}<span>＋</span></button><input ref={input} className="hidden-input" type="file" accept="audio/mpeg,.mp3" multiple onChange={onImport}/></section>
 <section className="library"><div className="section-heading"><h3>Library</h3><button className="text-button" onClick={createPlaylist}>＋ New playlist</button></div><div className="playlist-tabs"><button className={activePlaylist==="all"?"selected":""} onClick={()=>setActivePlaylist("all")}>All tracks</button>{playlists.map(item=><button className={activePlaylist===item.id?"selected":""} onClick={()=>setActivePlaylist(item.id)} key={item.id}>{item.name}<small>{item.trackIds.length}</small></button>)}</div>
 {activePlaylist!=="all"&&<div className="playlist-meta"><span>{queue.length} {queue.length===1?"track":"tracks"}</span><button onClick={deleteActivePlaylist}>Delete playlist</button></div>}{tracks.length>0&&<label className="search"><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search your MP3s"/></label>}
 {!busy&&tracks.length===0?<div className="empty"><div>♫</div><h3>No MP3s yet</h3><p>Tap “Choose MP3s” and select as many files as you want.</p></div>:queue.length===0?<div className="empty compact"><h3>This playlist is empty</h3><p>Open All tracks and tap ＋ beside a song.</p></div>:<div className="track-list">{visible.map((track,index)=><article className={`track ${current?.id===track.id?"active":""}`} key={track.id}><button className="track-main" onClick={()=>play(track)}><span className="number">{String(index+1).padStart(2,"0")}</span><span className="track-copy"><strong>{track.name}</strong><small>{formatBytes(track.size)} · MP3</small></span><span className="play">▶</span></button>{playlists.length>0&&<button className="track-action" onClick={()=>setAddingTrack(track)} aria-label={`Add ${track.name} to playlist`}>＋</button>}<button className="delete" onClick={()=>remove(track)} aria-label={`Remove ${track.name}`}>×</button></article>)}</div>}</section>
 {addingTrack&&<div className="sheet-backdrop" onClick={()=>setAddingTrack(null)}><section className="sheet" onClick={event=>event.stopPropagation()}><div className="sheet-handle"/><p className="eyebrow">ADD TO PLAYLIST</p><h3>{addingTrack.name}</h3>{playlists.map(item=><button onClick={()=>addToPlaylist(item.id,addingTrack.id)} key={item.id}><span>{item.name}</span><span>{item.trackIds.includes(addingTrack.id)?"✓":"＋"}</span></button>)}</section></div>}
 {current&&audioUrl&&<footer className="player"><div className="now-playing"><small>NOW PLAYING</small><strong>{current.name}</strong></div><div className="transport"><button onClick={()=>setShuffle(value=>!value)} className={shuffle?"enabled":""} aria-label="Shuffle">⇄</button><button onClick={()=>move("previous")} aria-label="Previous track">◀</button><audio key={audioUrl} src={audioUrl} controls autoPlay onEnded={()=>move("next")}/><button onClick={()=>move("next")} aria-label="Next track">▶</button><button onClick={cycleRepeat} className={repeat!=="off"?"enabled":""} aria-label={`Repeat ${repeat}`}>{repeat==="one"?"↻¹":"↻"}</button></div></footer>}</main>
}
