"use client";
import{ChangeEvent,useEffect,useMemo,useRef,useState}from"react";
import{nextTrackId,previousTrackId,RepeatMode}from"@/lib/queue";
import{playerGesture}from"@/lib/gestures";
import{formatBytes,importTracks,listTracks,removeTrack,renameTrack,Track}from"@/lib/tracks";
type Playlist={id:string;name:string;trackIds:string[]};
type AirPlayAudio=HTMLAudioElement&{webkitShowPlaybackTargetPicker?:()=>void;webkitCurrentPlaybackTargetIsWireless?:boolean};
function Artwork({track,size="small"}:{track:Track;size?:"small"|"large"}){const[url,setUrl]=useState<string>();useEffect(()=>{if(!track.artwork)return;const next=URL.createObjectURL(track.artwork);setUrl(next);return()=>URL.revokeObjectURL(next)},[track.artwork]);return <span className={`artwork ${size}`}>{url?<img src={url} alt=""/>:<span>♫</span>}</span>}
const slides=[{icon:"♫",title:"Your music, finally organized",copy:"Import a whole group of MP3s once. MP3 Shelf keeps them together so you can stop hunting through Files."},{icon:"⌕",title:"Find any track fast",copy:"Search titles and artists, build playlists, rename tracks and keep everything available offline."},{icon:"↻",title:"Built for listening",copy:"Use shuffle, repeat and automatic next-track playback from an app made to feel at home on iPhone."}];
function formatTime(seconds:number){if(!Number.isFinite(seconds))return"0:00";const minutes=Math.floor(seconds/60),rest=Math.floor(seconds%60);return `${minutes}:${String(rest).padStart(2,"0")}`}
export function MusicLibrary(){
 const[tracks,setTracks]=useState<Track[]>([]),[query,setQuery]=useState(""),[current,setCurrent]=useState<Track|null>(null),[audioUrl,setAudioUrl]=useState<string>(),[busy,setBusy]=useState(true),[shuffle,setShuffle]=useState(false),[repeat,setRepeat]=useState<RepeatMode>("off"),[playlists,setPlaylists]=useState<Playlist[]>([]),[activePlaylist,setActivePlaylist]=useState("all"),[addingTrack,setAddingTrack]=useState<Track|null>(null),[onboarding,setOnboarding]=useState(false),[slide,setSlide]=useState(0),[fullPlayer,setFullPlayer]=useState(false),[elapsed,setElapsed]=useState(0),[duration,setDuration]=useState(0),[playing,setPlaying]=useState(false),[volume,setVolume]=useState(1),[supportsVolume,setSupportsVolume]=useState(true),[airPlayAvailable,setAirPlayAvailable]=useState(false),[airPlayActive,setAirPlayActive]=useState(false);const input=useRef<HTMLInputElement>(null),audio=useRef<HTMLAudioElement>(null),gestureStart=useRef<{x:number;y:number}|null>(null);
 const refresh=async()=>setTracks(await listTracks());
 useEffect(()=>{refresh().finally(()=>setBusy(false));try{setPlaylists(JSON.parse(localStorage.getItem("mp3-shelf-playlists")??"[]"));setOnboarding(!localStorage.getItem("mp3-shelf-onboarded"))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("mp3-shelf-playlists",JSON.stringify(playlists))},[playlists]);
 useEffect(()=>()=>{if(audioUrl)URL.revokeObjectURL(audioUrl)},[audioUrl]);
 useEffect(()=>{const element=audio.current as AirPlayAudio|null;if(!element)return;element.setAttribute("x-webkit-airplay","allow");const isiOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1);setSupportsVolume(!isiOS);setAirPlayAvailable(typeof element.webkitShowPlaybackTargetPicker==="function");const update=()=>setAirPlayActive(Boolean(element.webkitCurrentPlaybackTargetIsWireless));element.addEventListener("webkitcurrentplaybacktargetiswirelesschanged",update);return()=>element.removeEventListener("webkitcurrentplaybacktargetiswirelesschanged",update)},[audioUrl]);
 const playlist=playlists.find(item=>item.id===activePlaylist),queue=useMemo(()=>playlist?tracks.filter(track=>playlist.trackIds.includes(track.id)):tracks,[playlist,tracks]),visible=useMemo(()=>queue.filter(track=>`${track.name} ${track.artist??""}`.toLowerCase().includes(query.toLowerCase().trim())),[queue,query]);
 useEffect(()=>{if(!current||!("mediaSession"in navigator))return;const artworkUrl=current.artwork?URL.createObjectURL(current.artwork):new URL("/icon-512.png",location.href).href;navigator.mediaSession.metadata=new MediaMetadata({title:current.name,artist:current.artist||"MP3 Shelf",album:current.album||"",artwork:[{src:artworkUrl,sizes:"512x512",type:current.artwork?.type||"image/png"}]});const set=(action:MediaSessionAction,handler:MediaSessionActionHandler)=>{try{navigator.mediaSession.setActionHandler(action,handler)}catch{}};set("play",()=>audio.current?.play());set("pause",()=>audio.current?.pause());set("previoustrack",()=>move("previous"));set("nexttrack",()=>move("next"));set("seekbackward",details=>seek(Math.max(0,(audio.current?.currentTime||0)-(details.seekOffset||10))));set("seekforward",details=>seek(Math.min(audio.current?.duration||0,(audio.current?.currentTime||0)+(details.seekOffset||10))));set("seekto",details=>{if(details.seekTime!=null)seek(details.seekTime)});return()=>{for(const action of["play","pause","previoustrack","nexttrack","seekbackward","seekforward","seekto"]as MediaSessionAction[])try{navigator.mediaSession.setActionHandler(action,null)}catch{}if(current.artwork)URL.revokeObjectURL(artworkUrl)}},[current,audioUrl,queue,shuffle,repeat]);
 useEffect(()=>{if("mediaSession"in navigator)navigator.mediaSession.playbackState=playing?"playing":"paused"},[playing]);
 useEffect(()=>{if(!("mediaSession"in navigator)||!duration||!Number.isFinite(duration))return;try{navigator.mediaSession.setPositionState({duration,playbackRate:audio.current?.playbackRate||1,position:Math.min(elapsed,duration)})}catch{}},[elapsed,duration]);
 async function onImport(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files??[]);if(!files.length)return;setBusy(true);try{await importTracks(files);await refresh()}finally{setBusy(false);event.target.value=""}}
 function play(track:Track){if(audioUrl)URL.revokeObjectURL(audioUrl);setElapsed(0);setDuration(0);setCurrent(track);setAudioUrl(URL.createObjectURL(track.blob))}
 function move(direction:"next"|"previous"){if(!current)return;const ids=queue.map(track=>track.id),id=direction==="next"?nextTrackId(ids,current.id,{shuffle,repeat}):previousTrackId(ids,current.id),target=tracks.find(track=>track.id===id);if(target)play(target)}
 async function remove(track:Track){await removeTrack(track.id);setPlaylists(items=>items.map(item=>({...item,trackIds:item.trackIds.filter(id=>id!==track.id)})));if(current?.id===track.id){setCurrent(null);setAudioUrl(undefined)}await refresh()}
 async function rename(track:Track){const name=window.prompt("Track name",track.name)?.trim();if(!name||name===track.name)return;await renameTrack(track.id,name);if(current?.id===track.id)setCurrent({...current,name});await refresh()}
 function createPlaylist(){const name=window.prompt("Playlist name")?.trim();if(!name)return;const id=crypto.randomUUID();setPlaylists(items=>[...items,{id,name,trackIds:[]}]);setActivePlaylist(id)}
 function addToPlaylist(playlistId:string,trackId:string){setPlaylists(items=>items.map(item=>item.id===playlistId&&!item.trackIds.includes(trackId)?{...item,trackIds:[...item.trackIds,trackId]}:item));setAddingTrack(null)}
 function deleteActivePlaylist(){if(activePlaylist==="all")return;setPlaylists(items=>items.filter(item=>item.id!==activePlaylist));setActivePlaylist("all")}
 function reorderPlaylist(direction:-1|1){const index=playlists.findIndex(item=>item.id===activePlaylist),target=index+direction;if(index<0||target<0||target>=playlists.length)return;setPlaylists(items=>{const next=[...items];[next[index],next[target]]=[next[target],next[index]];return next})}
 function cycleRepeat(){setRepeat(mode=>mode==="off"?"all":mode==="all"?"one":"off")}
 function finishOnboarding(){localStorage.setItem("mp3-shelf-onboarded","true");setOnboarding(false)}
 function togglePlayback(){if(!audio.current)return;if(audio.current.paused)audio.current.play();else audio.current.pause()}
 function seek(value:number){if(!audio.current)return;audio.current.currentTime=value;setElapsed(value)}
 function changeVolume(value:number){if(!audio.current)return;audio.current.volume=value;setVolume(value)}
 function showAirPlay(){(audio.current as AirPlayAudio|null)?.webkitShowPlaybackTargetPicker?.()}
 function startGesture(event:React.PointerEvent){gestureStart.current={x:event.clientX,y:event.clientY}}
 function endGesture(event:React.PointerEvent){if(!gestureStart.current)return;const action=playerGesture(event.clientX-gestureStart.current.x,event.clientY-gestureStart.current.y);gestureStart.current=null;if(action==="close")setFullPlayer(false);else if(action==="next")move("next");else if(action==="previous")move("previous")}
 return <main className="shell"><header className="topbar"><div className="brand-mark">♫</div><div><p className="eyebrow">YOUR OFFLINE LIBRARY</p><h1>MP3 Shelf</h1></div><button className="add-small" onClick={()=>input.current?.click()} aria-label="Import MP3 files">＋</button></header>
 <section className="hero"><p className="eyebrow accent">FILES, WITHOUT THE HUNT</p><h2>Pick them once.<br/>Play them anytime.</h2><p>Choose a whole group of MP3s from Files, then search, organize and play them here.</p><button className="import-button" onClick={()=>input.current?.click()} disabled={busy}>{busy?"Loading…":"Choose MP3s"}<span>＋</span></button><input ref={input} className="hidden-input" type="file" accept="audio/mpeg,.mp3" multiple onChange={onImport}/></section>
 <section className="library"><div className="section-heading"><h3>Library</h3><button className="text-button" onClick={createPlaylist}>＋ New playlist</button></div><div className="playlist-tabs"><button className={activePlaylist==="all"?"selected":""} onClick={()=>setActivePlaylist("all")}>All tracks</button>{playlists.map(item=><button className={activePlaylist===item.id?"selected":""} onClick={()=>setActivePlaylist(item.id)} key={item.id}>{item.name}<small>{item.trackIds.length}</small></button>)}</div>
 {activePlaylist!=="all"&&<div className="playlist-meta"><div><button onClick={()=>reorderPlaylist(-1)} aria-label="Move playlist left">←</button><button onClick={()=>reorderPlaylist(1)} aria-label="Move playlist right">→</button><span>{queue.length} {queue.length===1?"track":"tracks"}</span></div><button onClick={deleteActivePlaylist}>Delete playlist</button></div>}{tracks.length>0&&<label className="search"><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search titles or artists"/></label>}
 {!busy&&tracks.length===0?<div className="empty"><div>♫</div><h3>No MP3s yet</h3><p>Tap “Choose MP3s” and select as many files as you want.</p></div>:queue.length===0?<div className="empty compact"><h3>This playlist is empty</h3><p>Open All tracks and tap ＋ beside a song.</p></div>:<div className="track-list">{visible.map((track,index)=><article className={`track ${current?.id===track.id?"active":""}`} key={track.id}><button className="track-main has-art" onClick={()=>play(track)}><Artwork track={track}/><span className="track-copy"><strong>{track.name}</strong><small>{track.artist?[track.artist,track.album].filter(Boolean).join(" · "):`${formatBytes(track.size)} · MP3`}</small></span><span className="play">▶</span></button><button className="track-action rename" onClick={()=>rename(track)} aria-label={`Rename ${track.name}`}>✎</button>{playlists.length>0&&<button className="track-action" onClick={()=>setAddingTrack(track)} aria-label={`Add ${track.name} to playlist`}>＋</button>}<button className="delete" onClick={()=>remove(track)} aria-label={`Remove ${track.name}`}>×</button></article>)}</div>}</section>
 {addingTrack&&<div className="sheet-backdrop" onClick={()=>setAddingTrack(null)}><section className="sheet" onClick={event=>event.stopPropagation()}><div className="sheet-handle"/><p className="eyebrow">ADD TO PLAYLIST</p><h3>{addingTrack.name}</h3>{playlists.map(item=><button onClick={()=>addToPlaylist(item.id,addingTrack.id)} key={item.id}><span>{item.name}</span><span>{item.trackIds.includes(addingTrack.id)?"✓":"＋"}</span></button>)}</section></div>}
 {current&&audioUrl&&<footer className="player"><button className="now-playing" onClick={()=>setFullPlayer(true)}><Artwork track={current}/><span><small>NOW PLAYING</small><strong>{current.name}</strong></span><b>⌃</b></button><div className="transport"><button onClick={()=>setShuffle(value=>!value)} className={shuffle?"enabled":""} aria-label="Shuffle">⇄</button><button onClick={()=>move("previous")} aria-label="Previous track">◀</button><audio ref={audio} key={audioUrl} src={audioUrl} controls autoPlay onLoadedMetadata={event=>setDuration(event.currentTarget.duration)} onTimeUpdate={event=>setElapsed(event.currentTarget.currentTime)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>move("next")}/><button onClick={()=>move("next")} aria-label="Next track">▶</button><button onClick={cycleRepeat} className={repeat!=="off"?"enabled":""} aria-label={`Repeat ${repeat}`}>{repeat==="one"?"↻¹":"↻"}</button></div></footer>}
 {fullPlayer&&current&&<section className="full-player"><header><button onClick={()=>setFullPlayer(false)} aria-label="Close full-screen player">⌄</button><span>NOW PLAYING</span><i/></header><div className="gesture-zone" onPointerDown={startGesture} onPointerUp={endGesture}><div className="cover"><Artwork track={current} size="large"/></div><div className="full-track"><h2>{current.name}</h2><p>{[current.artist,current.album].filter(Boolean).join(" · ")||"MP3 Shelf"}</p></div></div><div className="scrubber"><input type="range" min="0" max={duration||0} step="0.1" value={Math.min(elapsed,duration||0)} onChange={event=>seek(Number(event.target.value))} style={{"--progress":`${duration?elapsed/duration*100:0}%`} as React.CSSProperties}/><div><span>{formatTime(elapsed)}</span><span>-{formatTime(Math.max(0,duration-elapsed))}</span></div></div><div className="full-controls"><button onClick={()=>setShuffle(value=>!value)} className={shuffle?"enabled":""} aria-label="Shuffle">⇄</button><button onClick={()=>move("previous")} aria-label="Previous track">◀</button><button className="main-play" onClick={togglePlayback} aria-label={playing?"Pause":"Play"}>{playing?"Ⅱ":"▶"}</button><button onClick={()=>move("next")} aria-label="Next track">▶</button><button onClick={cycleRepeat} className={repeat!=="off"?"enabled":""} aria-label={`Repeat ${repeat}`}>{repeat==="one"?"↻¹":"↻"}</button></div><div className="output-controls">{supportsVolume?<label className="volume"><span>{volume===0?"⌁":"◖"}</span><input type="range" min="0" max="1" step="0.01" value={volume} onChange={event=>changeVolume(Number(event.target.value))} aria-label="Volume"/><span>◗</span></label>:<span className="ios-volume">Use the iPhone side buttons for volume</span>}{airPlayAvailable&&<button className={airPlayActive?"airplay active":"airplay"} onClick={showAirPlay} aria-label="Choose AirPlay device"><span>▱</span>{airPlayActive?"Playing with AirPlay":"AirPlay"}</button>}</div></section>}
 {onboarding&&<div className="onboarding"><button className="skip" onClick={finishOnboarding}>Skip</button><div className="onboard-mark">{slides[slide].icon}</div><p className="eyebrow accent">WELCOME TO MP3 SHELF</p><h2>{slides[slide].title}</h2><p>{slides[slide].copy}</p><div className="dots">{slides.map((_,index)=><span className={index===slide?"active":""} key={index}/>)}</div><button className="import-button" onClick={()=>slide<slides.length-1?setSlide(slide+1):finishOnboarding()}>{slide<slides.length-1?"Continue":"Start importing"}<span>→</span></button></div>}
 </main>
}
